"""updated job model

Revision ID: c88014e0b0f2
Revises: ad9dde58be01
Create Date: 2026-05-18 13:58:12.517264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88014e0b0f2'
down_revision: Union[str, Sequence[str], None] = 'ad9dde58be01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('source', sa.String(), server_default='internal', nullable=False))
    op.alter_column('jobs', 'employer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'jobs', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='unique')
    op.alter_column('jobs', 'employer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('jobs', 'source')
    op.drop_column('jobs', 'external_id')
    # ### end Alembic commands ###
